### ISSUE TITLE
Clarify PCIe slot description on SBCs

### ISSUE THREAD

**Issue by fire219** [TheRetroWeb/TRW-Issues#33]
![](https://cdn.discordapp.com/attachments/795405655468277811/883467148784201778/unknown.png)

Changing the wording to "1x PCIe 2.0 x4" or "1x PCIe x4 2.0" (for example) would be clearer to the user.

**Comment by drninkeo** [comment]
The technical meaning would be **1x PCI Express x4**, but as long as any confusion is removed, its not a serious issue

**Comment by TheRealZago** [comment]
Late answer, I know

I'll have to implement some form of port-specific template string, because some ports sound better in other forms. This will take a while.

**Comment by TheRealZago** [comment]
Obsoleted by the merger with Ultimate Retro.

The final database currently lacks a way to specify these finer details, they might be added on a later date.
