### ISSUE TITLE
Website incorrectly loading in legacy mode

### ISSUE THREAD

**Issue by suppenschussel** [TheRetroWeb/TRW-Issues#42]
The User-Agent parsing method breaks when the browser version is greater than **99**, this causes it to detect incorrectly as **version 0.0** and load in legacy mode.

### User-Agent strings tested:
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36
Mozilla/5.0 (Macintosh; Intel Mac OS X 12_3_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 12.3; rv:101.0) Gecko/20100101 Firefox/101.0
Mozilla/5.0 (X11; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0
```

**Comment by TheRealZago** [comment]
Thanks for the report,
Unfortunately I'm unable to replicate the issue with MSEdge 100 (`User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36 Edg/100.0.1185.36`) and MSEdge 101 (`User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36 Edg/101.0.1210.32`).
I can only replicate the issue with Firefox and Opera, it looks like they're not exposing the browser version correctly in the UA and, by default, unidentified engines are left on legacy mode.

For the time being, I'll simply partially bypass the filter. There's a new engine in the works and legacy mode will be relegated to its dedicated subdomain anyway for easier maintenance and to avoid issues like these.

**Comment by TheRealZago** [comment]
Legacy browsers will be dealt with after the merger with Ultimate Retro.

Reminder at https://gitlab.com/ultimateretro/ultimateretro/-/issues/22
